### ISSUE TITLE
Test Device: File Size persistence? 

### ISSUE THREAD

**Issue by enderesting** [padrezulmiro/segc-035-T1F1#16]
This is more of a question than an issue. Should the file size be re-assigned every time Server goes down? Should it be persistent and written in a file somewhere?

**Comment by padrezulmiro** [comment]
This likely needs to be persistent and written in a file. I don't think there's any way to avoid that. Currently you have:
https://github.com/padrezulmiro/segc-035-T1F1/blob/ef60659cfb501f31817b87625126d62bc9190767/iotserver/ServerManager.java#L64-L71
\- which will not work if the `.class` file doesn't exist. And we shouldn't assume it will exist since the server wouldn't usually have access to it in a realistic scenario.

**Comment by enderesting** [comment]
The professor's explanation for this is to have it hardcoded in file or get the file's size through a script. We can handle this later
